// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ8lrA7dClTYoo-RNiCuDNw9iO_5DQjsQ',
    appId: '1:356129719413:web:0622cd28774f432772e43c',
    messagingSenderId: '356129719413',
    projectId: 'shop-app-b5606',
    authDomain: 'shop-app-b5606.firebaseapp.com',
    databaseURL:
        'https://shop-app-b5606-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shop-app-b5606.appspot.com',
    measurementId: 'G-GXL4R52WHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMq3--P57FsjASUHhsb1p4bSilvXC7CWk',
    appId: '1:356129719413:android:23f31f720d22efd172e43c',
    messagingSenderId: '356129719413',
    projectId: 'shop-app-b5606',
    databaseURL:
        'https://shop-app-b5606-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shop-app-b5606.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe0Ur9oJFV_FxFzn1Cct257ZGTStuXLQo',
    appId: '1:356129719413:ios:dd704901523c393f72e43c',
    messagingSenderId: '356129719413',
    projectId: 'shop-app-b5606',
    databaseURL:
        'https://shop-app-b5606-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shop-app-b5606.appspot.com',
    iosClientId:
        '356129719413-a8ejs2aoci1fgos8n4ur484hnnbdv82i.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe0Ur9oJFV_FxFzn1Cct257ZGTStuXLQo',
    appId: '1:356129719413:ios:dd704901523c393f72e43c',
    messagingSenderId: '356129719413',
    projectId: 'shop-app-b5606',
    databaseURL:
        'https://shop-app-b5606-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shop-app-b5606.appspot.com',
    iosClientId:
        '356129719413-a8ejs2aoci1fgos8n4ur484hnnbdv82i.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
